-- LEGACY V1 MIGRATION (NO-OP)
-- --------------------------------------------
-- This file originally created the entire first
-- version of the schema (roles/users/banks/etc).
--
-- To avoid duplicate table creation and FK issues
-- when initializing a brand new database, this
-- migration has been intentionally converted to a
-- NO-OP. The canonical schema for new databases
-- is now defined in:
--   - 01_create_all_tables.sql
--   - later incremental migrations.
--
-- The file is kept (with the same name) so that
-- existing databases which have already applied it
-- remain compatible with Cloudflare D1's migration
-- history, but running it on a new database does
-- nothing.

-- NO-OP to keep SQL parser happy
SELECT 1;
