-- Add salary data for existing employees
INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-2 months'), basic_salary, housing_allowance, transportation_allowance, 0, 1000, 500, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance + 1500, 0, basic_salary + housing_allowance + transportation_allowance + 1500, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP001';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-1 months'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 100, 0, 0, basic_salary + housing_allowance + transportation_allowance, 100, basic_salary + housing_allowance + transportation_allowance - 100, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP001';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'approved', 1 FROM hr_employees WHERE employee_code = 'EMP001';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-2 months'), basic_salary, housing_allowance, transportation_allowance, 0, 2000, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance + 2000, 0, basic_salary + housing_allowance + transportation_allowance + 2000, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP002';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-1 months'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 150, 0, 0, basic_salary + housing_allowance + transportation_allowance, 150, basic_salary + housing_allowance + transportation_allowance - 150, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP002';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'pending', 1 FROM hr_employees WHERE employee_code = 'EMP002';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-2 months'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP003';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-1 months'), basic_salary, housing_allowance, transportation_allowance, 0, 500, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance + 500, 0, basic_salary + housing_allowance + transportation_allowance + 500, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP003';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'approved', 1 FROM hr_employees WHERE employee_code = 'EMP003';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-2 months'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 500, 0, basic_salary + housing_allowance + transportation_allowance, 500, basic_salary + housing_allowance + transportation_allowance - 500, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP004';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-1 months'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP004';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'pending', 1 FROM hr_employees WHERE employee_code = 'EMP004';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-2 months'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP005';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month', '-1 months'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'paid', 1 FROM hr_employees WHERE employee_code = 'EMP005';

INSERT OR IGNORE INTO hr_salaries (employee_id, salary_month, basic_salary, housing_allowance, transportation_allowance, other_allowances, bonuses, overtime_amount, late_deductions, absence_deductions, other_deductions, gross_salary, total_deductions, net_salary, payment_status, tenant_id)
SELECT id, date('now', 'start of month'), basic_salary, housing_allowance, transportation_allowance, 0, 0, 0, 0, 0, 0, basic_salary + housing_allowance + transportation_allowance, 0, basic_salary + housing_allowance + transportation_allowance, 'pending', 1 FROM hr_employees WHERE employee_code = 'EMP005';
